version: '3.8'

volumes:
  neo4j-data:

services:

  #
  # NGINX is probably overkill for now: Neo4j is potentially
  # self-sufficient for our use cases, especially after future SSL hardening
  #  nginx:
  #    image: nginx:latest
  #    ports:
  #      - 80:80
  #      - 443:443
  #    # volumes:
  #    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    depends_on:
  #      - neo4j

  neo4j:
    image: neo4j:4.4
    env_file:
      - .env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
      - ./dumps:/dumps
      - ./scripts:/scripts
      - ./neo4j:/var/lib/neo4j/conf
    # NEO4J_DUMP_FILENAME can be defined within the .env file
    entrypoint: /scripts/load_and_boot_neo4j.sh $NEO4J_DUMP_FILENAME
